### ISSUE TITLE
Not able to Set CurrencyCode to StandardField

### ISSUE THREAD

**Issue by nitinpatil** [tomasmcguinness/dotnet-passbook#112]
Hello,

I have tried to set CurrencyCode to Standard Field but in the library, we cant set the CurrencyCode to StandardField object, there is no such property.

Is there any other way available to set currency code?

Thanks,
Nitin

**Comment by tomasmcguinness** [comment]
Hi. Can you give me an example of what you're trying to do?

**Comment by nitinpatil** [comment]
Hi..

I am trying to build SoteCard pass dynamically and it has some value say 100, but I want to set currency symbol as well.  So on the pass, it should display £ 100 as StoreCard amount.

Do you need any other details?

Thanks,
Nitin

**Comment by tomasmcguinness** [comment]
Thank, Nitin,

Let me take a look today or tomorrow and I'll get back to you.

Tom

**Comment by tomasmcguinness** [comment]
Hi,

I've taken a look at the code. The CurrencyCode property exists on the NumberField. Use this instead of the StandardField to store the value.

Please let me know if this helps!

If you find dotnet-passbook useful, please consider donating to help keep the project updated - https://www.buymeacoffee.com/fMKJ2NnQ3

**Comment by nitinpatil** [comment]
Thank You, its working with the help of NumberField.
