### ISSUE TITLE
Passbook install fails on Chrome for iOS

### ISSUE THREAD

**Issue by carol-braileanu** [tomasmcguinness/dotnet-passbook#48]
Hello,

I have a couple of issues trying to create my .pkpass files using dotnet-passbook.
I was able to create a pkpass file but it will not install from Chrome on iOS. (see safari.zip). It works from Safari and Mail, but on Chrome I get an error saying "sorry, your pass cannot be installed to Passbook at this time. 

Another problem I have is with the same pass, if I try to set RelevantDate or Expiration date. In those cases the pass is not valid anymore and is not being loaded from any browser / app. (see relevantDate.zip)

[safari.zip](https://github.com/tomasmcguinness/dotnet-passbook/files/720968/safari.zip)
[relevantDate.zip](https://github.com/tomasmcguinness/dotnet-passbook/files/720967/relevantDate.zip)

**Comment by tomasmcguinness** [comment]
Let me take a look. The first issue might be a problem with the Browser, rather than the pass itself, since the pass is completely self contained.

**Comment by jiggak** [comment]
The second issue with the `RelevantDate` appears to be due to the date format in the output. Here is an entry from the system log for the error.

    Apr  5 13:34:12 Macintosh.local MobileSafari[341]: Invalid data error reading pass pass.com.envisageny.Engage360/[snip]. Unable to parse relevantDate 2017-04-05T20:00:00 as a date. We expect dates in "W3C date time stamp format", either "Complete date plus hours and minutes" or "Complete date plus hours, minutes and seconds". For example, 1980-05-07T10:30-05:00.
    Apr  5 13:34:12 Macintosh.local MobileSafari[341]: PassBook Pass download failed: The pass cannot be read because it isn’t valid.

And from `pass.json`

    "relevantDate": "2017-04-05T20:00:00"

Not sure yet if this is a problem in the library or something to do with the `DateTime` instance used for `RelevantDate`.

**Comment by jiggak** [comment]
Found the source of the problem. The date/time format used [https://github.com/tomasmcguinness/dotnet-passbook/blob/master/Passbook.Generator/PassGeneratorRequest.cs#L392](here) is `yyyy-MM-ddTHH:mm:ssK`. The `K` char will output nothing for `DateTimeKind == Unspecified` which is *not* a valid W3C date/time.

The immediate solution is to ensure the `DateTime` instance passed in is in UTC. I'm not sure what the real solution should be. It wouldn't necessarily make sense for the passbook generator to do that conversion since it could result in a value the application developer isn't expecting. Perhaps throw an `ArgumentException` when relevant date has `DateTimeKind.Unspecified`?

**Comment by tomasmcguinness** [comment]
I'll take a look. Thanks.

**Comment by tomasmcguinness** [comment]
Closing this due to age.
