### ISSUE TITLE
Support dotnet standard

### ISSUE THREAD

**Issue by tommed** [tomasmcguinness/dotnet-passbook#86]
The cryptography library you're using could easily be using the one on nuget and this package migrated over to dotnet standard. Would then work with .net framework and .net core.

**Comment by jiggak** [comment]
It looks like @tomasmcguinness already did most (all?) of the work necessary for dotnet core in the branch `port-to-dotnet-standard`. I created a PR recently #85 that just removes the dependency on `System.Drawing` for this port.

So far my tests with this port have been looking good.

**Comment by tommed** [comment]
I can’t see it on nuget? ;)

**Comment by jiggak** [comment]
IMHO ideally we work with @tomasmcguinness to do whatever is necessary to get the dotnet standard port ready for release, rather than publish some forked build on nuget. But I suppose that is an option if it comes to it.

And yet another option is to add `dotnet-passbook` repo as a git sub-module to your project, and point it to the `port-to-dotnet-standard` branch, or my fork without the `System.Drawing` dependency.

**Comment by tomasmcguinness** [comment]
Sorry all! New baby arrived in the house, so been a little bit busy. @jiggak Thanks for the PR. I'll get that merged in the next week or so. 

My plan is to move the library to version 2.0 and publish to Nuget.

Thank you for your patience.

**Comment by tomasmcguinness** [comment]
Complete by #91
